window.CSC_QUESTIONS = [
  {
    "id": "set-h-v3-2026-1",
    "itemNumber": 1,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "RA 6713 norms of conduct",
    "correctChoice": "D",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-2",
    "itemNumber": 2,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "1987 Constitution environmental right",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-3",
    "itemNumber": 3,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "RA 6713 response period",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-4",
    "itemNumber": 4,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "SALN coverage",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-5",
    "itemNumber": 5,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "Constitution indigenous peoples rights",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-6",
    "itemNumber": 6,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "environment agency DENR",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-7",
    "itemNumber": 7,
    "sourceImage": "image_03.jpg",
    "sourcePage": 3,
    "section": "General Information",
    "subtopic": "human rights non-derogable prohibition",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-8",
    "itemNumber": 8,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "rule of law",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-9",
    "itemNumber": 9,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "transparency in governance",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-10",
    "itemNumber": 10,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "CSC constitutional commission",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-11",
    "itemNumber": 11,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "Philippine territory sovereignty",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-12",
    "itemNumber": 12,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "solid waste management",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-13",
    "itemNumber": 13,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "separation of powers",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-14",
    "itemNumber": 14,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "RA 6713 prohibited acts",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-15",
    "itemNumber": 15,
    "sourceImage": "image_04.jpg",
    "sourcePage": 4,
    "section": "General Information",
    "subtopic": "public service promptness",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-16",
    "itemNumber": 16,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "General Information",
    "subtopic": "peace education",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-17",
    "itemNumber": 17,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "General Information",
    "subtopic": "Bill of Rights article",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-18",
    "itemNumber": 18,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "General Information",
    "subtopic": "accountability",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-19",
    "itemNumber": 19,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "General Information",
    "subtopic": "right against torture",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-20",
    "itemNumber": 20,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "General Information",
    "subtopic": "responsiveness in frontline service",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-21",
    "itemNumber": 21,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "Verbal Ability",
    "subtopic": "synonym in sentence",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-22",
    "itemNumber": 22,
    "sourceImage": "image_05.jpg",
    "sourcePage": 5,
    "section": "Verbal Ability",
    "subtopic": "synonym in sentence",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-23",
    "itemNumber": 23,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "synonym in sentence",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-24",
    "itemNumber": 24,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "synonym in sentence",
    "correctChoice": "D",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-25",
    "itemNumber": 25,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "synonym in sentence",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-26",
    "itemNumber": 26,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-27",
    "itemNumber": 27,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "D",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-28",
    "itemNumber": 28,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-29",
    "itemNumber": 29,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-30",
    "itemNumber": 30,
    "sourceImage": "image_06.jpg",
    "sourcePage": 6,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-31",
    "itemNumber": 31,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-32",
    "itemNumber": 32,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-33",
    "itemNumber": 33,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-34",
    "itemNumber": 34,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-35",
    "itemNumber": 35,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-36",
    "itemNumber": 36,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "word choice / commonly confused words",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-37",
    "itemNumber": 37,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "pronoun choice",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-38",
    "itemNumber": 38,
    "sourceImage": "image_07.jpg",
    "sourcePage": 7,
    "section": "Verbal Ability",
    "subtopic": "subject-verb agreement",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-39",
    "itemNumber": 39,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "word choice / lay-lie",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-40",
    "itemNumber": 40,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "spelling / word choice",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-41",
    "itemNumber": 41,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-42",
    "itemNumber": 42,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-43",
    "itemNumber": 43,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-44",
    "itemNumber": 44,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-45",
    "itemNumber": 45,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-46",
    "itemNumber": 46,
    "sourceImage": "image_08.jpg",
    "sourcePage": 8,
    "section": "Verbal Ability",
    "subtopic": "word choice",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-47",
    "itemNumber": 47,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "subject-verb agreement",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-48",
    "itemNumber": 48,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "conditional tense",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-49",
    "itemNumber": 49,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "subject-verb agreement",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-50",
    "itemNumber": 50,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "homophone choice",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-51",
    "itemNumber": 51,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension main idea",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-52",
    "itemNumber": 52,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension detail",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-53",
    "itemNumber": 53,
    "sourceImage": "image_09.jpg",
    "sourcePage": 9,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension inference",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-54",
    "itemNumber": 54,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "vocabulary in context",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-55",
    "itemNumber": 55,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension detail",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-56",
    "itemNumber": 56,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "vocabulary in context",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-57",
    "itemNumber": 57,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "antonym in sentence",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-58",
    "itemNumber": 58,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension detail",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-59",
    "itemNumber": 59,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "grammar correct sentence",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-60",
    "itemNumber": 60,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "grammar correct sentence",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-61",
    "itemNumber": 61,
    "sourceImage": "image_10.jpg",
    "sourcePage": 10,
    "section": "Verbal Ability",
    "subtopic": "synonym",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-62",
    "itemNumber": 62,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "synonym",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-63",
    "itemNumber": 63,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "antonym",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-64",
    "itemNumber": 64,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "antonym",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-65",
    "itemNumber": 65,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-66",
    "itemNumber": 66,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-67",
    "itemNumber": 67,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "word choice",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-68",
    "itemNumber": 68,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "word form",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-69",
    "itemNumber": 69,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "adverb choice",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-70",
    "itemNumber": 70,
    "sourceImage": "image_11.jpg",
    "sourcePage": 11,
    "section": "Verbal Ability",
    "subtopic": "word choice / homograph",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-71",
    "itemNumber": 71,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "reading comprehension main idea",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-72",
    "itemNumber": 72,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "vocabulary in context",
    "correctChoice": "C",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-73",
    "itemNumber": 73,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "vocabulary in context",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-74",
    "itemNumber": 74,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "spelling",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-75",
    "itemNumber": 75,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "spelling",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-76",
    "itemNumber": 76,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "spelling",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-77",
    "itemNumber": 77,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "spelling",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-78",
    "itemNumber": 78,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "spelling",
    "correctChoice": "A",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-79",
    "itemNumber": 79,
    "sourceImage": "image_12.jpg",
    "sourcePage": 12,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-80",
    "itemNumber": 80,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Verbal Ability",
    "subtopic": "error identification",
    "correctChoice": "B",
    "expectedSeconds": 45,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-81",
    "itemNumber": 81,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "basic operations / order of operations",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-82",
    "itemNumber": 82,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "percent word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-83",
    "itemNumber": 83,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "linear equation",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-84",
    "itemNumber": 84,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "probability word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-85",
    "itemNumber": 85,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "average word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-86",
    "itemNumber": 86,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "rate word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-87",
    "itemNumber": 87,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "fractions",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-88",
    "itemNumber": 88,
    "sourceImage": "image_13.jpg",
    "sourcePage": 13,
    "section": "Numerical Ability",
    "subtopic": "percent discount word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-89",
    "itemNumber": 89,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "geometry area",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-90",
    "itemNumber": 90,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "number sequence",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-91",
    "itemNumber": 91,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "algebraic expression",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-92",
    "itemNumber": 92,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "work rate word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-93",
    "itemNumber": 93,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "ratio",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-94",
    "itemNumber": 94,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "average word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-95",
    "itemNumber": 95,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "radicals and exponents",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-96",
    "itemNumber": 96,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "profit percent word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-97",
    "itemNumber": 97,
    "sourceImage": "image_14.jpg",
    "sourcePage": 14,
    "section": "Numerical Ability",
    "subtopic": "algebra word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-98",
    "itemNumber": 98,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "decimal to fraction",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-99",
    "itemNumber": 99,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "percent capacity word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-100",
    "itemNumber": 100,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "geometry perimeter",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-101",
    "itemNumber": 101,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "exponents / order of operations",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-102",
    "itemNumber": 102,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "linear equation",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-103",
    "itemNumber": 103,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "speed word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-104",
    "itemNumber": 104,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "GCF",
    "correctChoice": "C",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-105",
    "itemNumber": 105,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "LCM",
    "correctChoice": "C",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-106",
    "itemNumber": 106,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "consecutive numbers word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-107",
    "itemNumber": 107,
    "sourceImage": "image_15.jpg",
    "sourcePage": 15,
    "section": "Numerical Ability",
    "subtopic": "unit rate word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-108",
    "itemNumber": 108,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "map scale word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-109",
    "itemNumber": 109,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "algebraic expression",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-110",
    "itemNumber": 110,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "percent",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-111",
    "itemNumber": 111,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "function evaluation",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-112",
    "itemNumber": 112,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "arithmetic word problem",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-113",
    "itemNumber": 113,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "geometry volume",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-114",
    "itemNumber": 114,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "unit cost word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-115",
    "itemNumber": 115,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "linear equation",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-116",
    "itemNumber": 116,
    "sourceImage": "image_16.jpg",
    "sourcePage": 16,
    "section": "Numerical Ability",
    "subtopic": "fraction to decimal",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-117",
    "itemNumber": 117,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Numerical Ability",
    "subtopic": "speed conversion",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-118",
    "itemNumber": 118,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Numerical Ability",
    "subtopic": "geometry circumference",
    "correctChoice": "A",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-119",
    "itemNumber": 119,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Numerical Ability",
    "subtopic": "ratio word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-120",
    "itemNumber": 120,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Numerical Ability",
    "subtopic": "percent increase word problem",
    "correctChoice": "B",
    "expectedSeconds": 75,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-121",
    "itemNumber": 121,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-122",
    "itemNumber": 122,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-123",
    "itemNumber": 123,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-124",
    "itemNumber": 124,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "C",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-125",
    "itemNumber": 125,
    "sourceImage": "image_17.jpg",
    "sourcePage": 17,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-126",
    "itemNumber": 126,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-127",
    "itemNumber": 127,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-128",
    "itemNumber": 128,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-129",
    "itemNumber": 129,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-130",
    "itemNumber": 130,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-131",
    "itemNumber": 131,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-132",
    "itemNumber": 132,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-133",
    "itemNumber": 133,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-134",
    "itemNumber": 134,
    "sourceImage": "image_18.jpg",
    "sourcePage": 18,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-135",
    "itemNumber": 135,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-136",
    "itemNumber": 136,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "filing/process sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-137",
    "itemNumber": 137,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "alphanumeric sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-138",
    "itemNumber": 138,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-139",
    "itemNumber": 139,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "filing/process sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-140",
    "itemNumber": 140,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-141",
    "itemNumber": 141,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-142",
    "itemNumber": 142,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-143",
    "itemNumber": 143,
    "sourceImage": "image_19.jpg",
    "sourcePage": 19,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-144",
    "itemNumber": 144,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-145",
    "itemNumber": 145,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-146",
    "itemNumber": 146,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-147",
    "itemNumber": 147,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-148",
    "itemNumber": 148,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-149",
    "itemNumber": 149,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-150",
    "itemNumber": 150,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-151",
    "itemNumber": 151,
    "sourceImage": "image_20.jpg",
    "sourcePage": 20,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-152",
    "itemNumber": 152,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-153",
    "itemNumber": 153,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-154",
    "itemNumber": 154,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-155",
    "itemNumber": 155,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "word analogy",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-156",
    "itemNumber": 156,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-157",
    "itemNumber": 157,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-158",
    "itemNumber": 158,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-159",
    "itemNumber": 159,
    "sourceImage": "image_21.jpg",
    "sourcePage": 21,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-160",
    "itemNumber": 160,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-161",
    "itemNumber": 161,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-162",
    "itemNumber": 162,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-163",
    "itemNumber": 163,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-164",
    "itemNumber": 164,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-165",
    "itemNumber": 165,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "number sequence",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-166",
    "itemNumber": 166,
    "sourceImage": "image_22.jpg",
    "sourcePage": 22,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-167",
    "itemNumber": 167,
    "sourceImage": "image_23.jpg",
    "sourcePage": 23,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-168",
    "itemNumber": 168,
    "sourceImage": "image_23.jpg",
    "sourcePage": 23,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-169",
    "itemNumber": 169,
    "sourceImage": "image_23.jpg",
    "sourcePage": 23,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "A",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  },
  {
    "id": "set-h-v3-2026-170",
    "itemNumber": 170,
    "sourceImage": "image_23.jpg",
    "sourcePage": 23,
    "section": "Analytical Ability",
    "subtopic": "assumption / conclusion",
    "correctChoice": "B",
    "expectedSeconds": 70,
    "reviewStatus": "needs_prompt_transcription"
  }
];
